# Welcome to Jekyll!
#  dfksfds
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Virtual/Craft"
# author: AliCB
description: "I acknowledge the Gadigal and Wangal people of the Eora Nation, the Traditional Owners of the land I live and work on. I pay my respects to Elders past and present. Sovereignty has never been ceded, and this always was and always will be Aboriginal Land."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alicb3000
instagram_username: resculpted
#email

# Build settings
theme: minima


header_pages:
  - pages/index.md
  - pages/About.md
  - pages/Projects.md
  - pages/Blog.md
